[[inputs.nicctl]]
  [[inputs.nicctl.command_group]]
    interval = "5s"
    commands = [
      "sudo nicctl show port statistics --json",
      "sudo nicctl show lif statistics --json",
    ]

  [[inputs.nicctl.command_group]]
    interval = "30s"
    commands = [
      "sudo nicctl show card statistics packet-buffer --json",
    ]
