[[inputs.nicctl]]
  [[inputs.nicctl.command_group]]
    interval = "5s"
    commands = [
      "nicctl show port statistics",
      "nicctl show lif statistics",
    ]

  [[inputs.nicctl.command_group]]
    interval = "30s"
    commands = [
      "nicctl show card statistics packet-buffer",
    ]
